#!/usr/bin/env python3
"""
Export Paper-Quality Dispersion Snapshots from HTML JSON Data

Reads heatmap_v3_pm25.json and heatmap_v3_pm1.json (same data the interactive
HTML map uses) and exports each timestep as an individual publication-quality
PNG with:
  - OpenStreetMap background (map tiles)
  - Fixed lat/lon axes (same extent every frame)
  - Jet colormap with µg/m³ colorbar on the right
  - Source marker (★) and sensor markers (▲)
  - Frame timestamp label

Usage:
    python export_snapshots.py
"""

import json
import os
import numpy as np
from scipy.ndimage import gaussian_filter
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
import matplotlib.ticker as mticker
from PIL import Image

# ============================================================
# CONFIGURATION — EDIT THESE TO CONTROL THE OUTPUT
# ============================================================
DATA_DIR = os.path.dirname(os.path.abspath(__file__))

# JSON data files (generated by export_v3_points.py)
PM25_JSON = os.path.join(DATA_DIR, 'heatmap_v3_pm25.json')
PM1_JSON  = os.path.join(DATA_DIR, 'heatmap_v3_pm1.json')

# Output directories
PM25_OUT_DIR = os.path.join(DATA_DIR, 'snapshots_pm25')
PM1_OUT_DIR  = os.path.join(DATA_DIR, 'snapshots_pm1')

# ---- Map background ----
MAP_BG_PATH = os.path.join(DATA_DIR, 'map_bg.png')
# Geographic bounds of the stitched tile image [lon_min, lon_max, lat_min, lat_max]
MAP_BG_EXTENT = [-122.387695, -122.299805, 47.606163, 47.665387]

# ---- Color scale ----
COLORMAP   = 'jet'         # matplotlib colormap name
VMIN       = 0             # min µg/m³ on colorbar
VMAX       = 50            # max µg/m³ on colorbar  (≥50 shown as deep red)
ALPHA_CAL  = 14.02         # calibration factor: grid_count × ALPHA_CAL = µg/m³
HEATMAP_ALPHA = 0.65       # transparency of heatmap overlay (0=invisible, 1=opaque)

# ---- Grid for binning points ----
GRID_RES_DEG = 0.0004      # ~45 m grid cells in degrees
SMOOTH_SIGMA = 2.5         # Gaussian smoothing sigma (grid cells)

# ---- Fixed map extent (same for every frame) ----
LAT_MIN = 47.615
LAT_MAX = 47.665
LON_MIN = -122.370
LON_MAX = -122.300

# ---- Figure size & DPI ----
FIG_WIDTH  = 8    # inches
FIG_HEIGHT = 7    # inches
DPI        = 200

# ---- Markers ----
# Ground truth fireworks source
SOURCE_LAT = 47.6403
SOURCE_LON = -122.3352

SENSOR_LOCS = {
    'S1': (47.6378, -122.3295),
    'S2': (47.6469, -122.3263),
    'S3': (47.6493, -122.3316),
    'S5': (47.6299, -122.3394),
    'S6': (47.6267, -122.3353),
}


# ============================================================
# MAP BACKGROUND
# ============================================================
def load_map_background():
    """Load the stitched OSM tile background image."""
    if os.path.exists(MAP_BG_PATH):
        img = np.array(Image.open(MAP_BG_PATH))
        print(f"  Map background loaded: {img.shape}")
        return img
    else:
        print(f"  WARNING: {MAP_BG_PATH} not found. Using plain background.")
        return None


# ============================================================
# CORE FUNCTIONS
# ============================================================
def load_json(filepath):
    """Load the heatmap JSON data."""
    print(f"Loading {filepath}...")
    with open(filepath, 'r') as f:
        data = json.load(f)
    print(f"  pm_type: {data['pm_type']}, frames: {len(data['time_labels'])}, "
          f"global_max weight: {data['global_max']:.2f}")
    return data


def bin_points_to_grid(points, lat_edges, lon_edges):
    """
    Bin point data [lat, lon, weight] onto a 2D grid.
    Returns 2D array (nlat × nlon).
    """
    if len(points) == 0:
        return np.zeros((len(lat_edges) - 1, len(lon_edges) - 1))

    pts = np.array(points)
    lats = pts[:, 0]
    lons = pts[:, 1]
    weights = pts[:, 2] if pts.shape[1] > 2 else np.ones(len(pts))

    grid, _, _ = np.histogram2d(
        lats, lons,
        bins=[lat_edges, lon_edges],
        weights=weights
    )
    return grid


def render_frame(grid_ugm3, lat_edges, lon_edges, time_label, pm_type,
                 frame_idx, output_path, map_bg):
    """Render a single publication-quality snapshot with map background."""

    fig, ax = plt.subplots(1, 1, figsize=(FIG_WIDTH, FIG_HEIGHT))

    # 1) Draw map background first
    if map_bg is not None:
        ax.imshow(map_bg, origin='upper',
                  extent=[MAP_BG_EXTENT[0], MAP_BG_EXTENT[1],
                          MAP_BG_EXTENT[2], MAP_BG_EXTENT[3]],
                  aspect='auto', zorder=0)

    # 2) Create RGBA heatmap overlay (transparent where concentration is zero)
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(vmin=VMIN, vmax=VMAX)
    heatmap_rgba = cmap(norm(grid_ugm3))

    # Make low-concentration areas transparent so map shows through
    # Alpha scales with concentration: 0 µg/m³ → fully transparent, VMAX → HEATMAP_ALPHA
    alpha_channel = np.clip(grid_ugm3 / (VMAX * 0.15), 0, 1) * HEATMAP_ALPHA
    heatmap_rgba[..., 3] = alpha_channel

    extent = [lon_edges[0], lon_edges[-1], lat_edges[0], lat_edges[-1]]

    im = ax.imshow(
        heatmap_rgba,
        origin='lower',
        extent=extent,
        aspect='auto',
        interpolation='bilinear',
        zorder=5,
    )

    # Create a ScalarMappable for the colorbar (since RGBA imshow doesn't auto-create one)
    sm = plt.cm.ScalarMappable(cmap=COLORMAP, norm=norm)
    sm.set_array([])

    # Source marker
    ax.plot(SOURCE_LON, SOURCE_LAT, '*', color='lime', markersize=18,
            markeredgecolor='black', markeredgewidth=1.5, zorder=20,
            label='Fireworks Source')

    # Sensor markers
    for sid, (slat, slon) in SENSOR_LOCS.items():
        if LAT_MIN <= slat <= LAT_MAX and LON_MIN <= slon <= LON_MAX:
            ax.plot(slon, slat, '^', color='white', markersize=9,
                    markeredgecolor='black', markeredgewidth=1.0, zorder=15)
            ax.annotate(sid, (slon, slat), textcoords='offset points',
                       xytext=(6, 6), fontsize=8, color='white',
                       fontweight='bold',
                       bbox=dict(boxstyle='round,pad=0.15',
                                facecolor='black', alpha=0.7),
                       zorder=16)

    # Axes
    ax.set_xlim(LON_MIN, LON_MAX)
    ax.set_ylim(LAT_MIN, LAT_MAX)
    ax.set_xlabel('Longitude (°W)', fontsize=12, fontweight='bold')
    ax.set_ylabel('Latitude (°N)', fontsize=12, fontweight='bold')
    ax.tick_params(labelsize=10)

    # Format tick labels
    ax.xaxis.set_major_formatter(mticker.FormatStrFormatter('%.3f°'))
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter('%.3f°'))
    ax.xaxis.set_major_locator(mticker.MaxNLocator(6))
    ax.yaxis.set_major_locator(mticker.MaxNLocator(6))

    # Title
    pm_label = 'PM$_{2.5}$' if pm_type == 'pm25' else 'PM$_1$'
    time_str = time_label.split(' ')[-1] if ' ' in time_label else time_label
    ax.set_title(f'{pm_label} Dispersion — {time_str} PDT',
                 fontsize=14, fontweight='bold', pad=12)

    # Colorbar
    cbar = fig.colorbar(sm, ax=ax, shrink=0.85, pad=0.03)
    cbar.set_label(f'{pm_label} Concentration (µg/m³)', fontsize=12,
                   fontweight='bold')
    cbar.ax.tick_params(labelsize=10)

    plt.tight_layout()
    plt.savefig(output_path, dpi=DPI, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close()


def process_dataset(json_path, output_dir, map_bg):
    """Process one JSON file and export all frames."""
    data = load_json(json_path)
    pm_type = data['pm_type']
    time_labels = data['time_labels']
    hm_data = data['hm_data']

    os.makedirs(output_dir, exist_ok=True)

    # Build grid edges
    lat_edges = np.arange(LAT_MIN, LAT_MAX + GRID_RES_DEG, GRID_RES_DEG)
    lon_edges = np.arange(LON_MIN, LON_MAX + GRID_RES_DEG, GRID_RES_DEG)

    n_frames = len(time_labels)
    print(f"\nExporting {n_frames} frames for {pm_type}...")

    for i in range(n_frames):
        points = hm_data[i]
        time_label = time_labels[i]

        # Bin points onto grid
        grid_raw = bin_points_to_grid(points, lat_edges, lon_edges)

        # Smooth
        grid_smooth = gaussian_filter(grid_raw, sigma=SMOOTH_SIGMA)

        # Convert to µg/m³
        grid_ugm3 = grid_smooth * ALPHA_CAL

        # Output filename
        time_str = time_label.replace(' ', '_').replace(':', '')
        fname = f'{pm_type}_dispersion_{time_str}.png'
        output_path = os.path.join(output_dir, fname)

        render_frame(grid_ugm3, lat_edges, lon_edges, time_label, pm_type,
                     i, output_path, map_bg)

        peak = grid_ugm3.max()
        n_pts = len(points)
        print(f"  [{i+1:2d}/{n_frames}] {time_label}  |  "
              f"{n_pts:5d} pts  |  peak {peak:6.1f} µg/m³  |  {fname}")

    print(f"\nDone — {n_frames} PNGs saved to {output_dir}/")


# ============================================================
# MAIN
# ============================================================
if __name__ == '__main__':
    print("=" * 65)
    print("  Paper-Quality Dispersion Snapshot Exporter")
    print("=" * 65)
    print(f"\n  Colormap:  {COLORMAP}")
    print(f"  Scale:     {VMIN}–{VMAX} µg/m³")
    print(f"  Extent:    {LAT_MIN}–{LAT_MAX}°N, {LON_MIN}–{LON_MAX}°W")
    print(f"  Grid:      {GRID_RES_DEG}° (~{GRID_RES_DEG * 111132:.0f} m)")
    print(f"  Smoothing: sigma = {SMOOTH_SIGMA} cells")
    print(f"  DPI:       {DPI}")

    # Load map background
    print("\nLoading map background...")
    map_bg = load_map_background()

    # Process PM2.5
    if os.path.exists(PM25_JSON):
        process_dataset(PM25_JSON, PM25_OUT_DIR, map_bg)
    else:
        print(f"\n  WARNING: {PM25_JSON} not found, skipping PM2.5")

    # Process PM1
    if os.path.exists(PM1_JSON):
        process_dataset(PM1_JSON, PM1_OUT_DIR, map_bg)
    else:
        print(f"\n  WARNING: {PM1_JSON} not found, skipping PM1")

    print("\n" + "=" * 65)
    print("  ALL DONE")
    print("=" * 65)
